# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

on:
  push:
    branches:
      - main

jobs:
  result-analyzer:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run:
          python create_model.py

      - name: Display training result
        run: cat report.txt
